### ISSUE TITLE
Toggle control visibility?

### ISSUE THREAD

**Issue by dseven** [maartenflippo/f1tv-tweaks#1]
Is it possible to toggle visibility of the controls at the bottom? One of the annoyances I have (when watching replays) is trying to get two players in sync by pausing one at a specific time then unpausing it when the other reaches that time .. but I have to keep wiggling mice to keep the controls from auto-hiding. Thanks!

**Comment by maartenflippo** [comment]
This is something I will add, but I am wondering how to go about controlling this feature. One of the possibilities would be to add a button to the player that would toggle this locked visibility status. Another option would be to add the toggle to a page action (clicking the extension icon in the browser toolbar and checking a box in a popup).

@dseven do you have a preference?

**Comment by dseven** [comment]
I was thinking of a keyboard shortcut. If it involves the extension icon, you'd have to leave full-screen mode to access it (?). I suppose maybe ideally it would be both a button in the player and a keyboard shortcut?

**Comment by maartenflippo** [comment]
Leaving fullscreen mode is undesirable indeed, that is a good point. I will start out with implementing it as a shortcut only, then see what can be done about the button.
