### ISSUE TITLE
Extension no longer works as of July 2020

### ISSUE THREAD

**Issue by Phoenix100k** [maartenflippo/f1tv-tweaks#17]
Not sure if this project is still active. The extension now appears greyed out on the current Chrome version (83.0.4). Even if set to use any site when you click the extension, it doesn't enlarge the player and keyboard shortcuts don't work. Any plans to update?

**Comment by MarkusTheOrt** [comment]
Hey there I've just pushed an update onto the fork on my account (I'll created a pull request #18 aswell)

**Comment by maartenflippo** [comment]
I have been a little pre-occupied given the covid situation, but I'll make sure new versions are published on Wednesday

**Comment by maartenflippo** [comment]
I am sorry for the delay, I have pushed updates to both the firefox and chrome extension repositories. The firefox one is live as of this comment, the chrome extension is pending review.
