### ISSUE TITLE
Multiple synced views

### ISSUE THREAD

**Issue by maartenflippo** [maartenflippo/f1tv-tweaks#3]
The F1TV app allows the selection of multiple views at once. This is probably a difficult feature to implement, but could have a great positive effect on the viewing experience. However, I need more information on how the streaming works.

**Comment by MarkusTheOrt** [comment]
If you have any questions on how to obtain the tokenised .m3u8 urls don't hesitate to ask me.

**Comment by maartenflippo** [comment]
I feel it is too easy for the extension to break, given the nature in which the f1tv web client is built, for this feature to be implemented successfully. Minor UI tweaks are easy to patch, but UI overhauls may be more difficult. That is why I am closing this issue for now. Given it has been open for almost a year and I have not found a solid way to do this. Maybe a new issue will be opened in the future where this can be implemented
